# Generated by Django 4.1.4 on 2023-01-19 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContasCasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField()),
                ('piscina', models.DecimalField(decimal_places=2, max_digits=10)),
                ('faxineira', models.DecimalField(decimal_places=2, max_digits=10)),
                ('internet', models.DecimalField(decimal_places=2, max_digits=10)),
                ('guarda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('luz', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agua', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra_iptu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('caixinha', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Morador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Divida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.CharField(max_length=100)),
                ('morador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contas_casa.morador')),
            ],
        ),
        migrations.CreateModel(
            name='ContaExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.CharField(max_length=100)),
                ('dono', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contas_casa.morador')),
            ],
        ),
    ]
