# Generated by Django 4.1.4 on 2023-01-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas_casa', '0002_contascasa_gas'),
    ]

    operations = [
        migrations.AddField(
            model_name='contascasa',
            name='pago',
            field=models.BooleanField(default=False),
        ),
    ]
